# Generated by Django 3.2.7 on 2021-11-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enter_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('reg', models.CharField(max_length=30)),
                ('mark', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Registration_Number',
        ),
    ]
