# Generated by Django 3.2.7 on 2021-11-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20211117_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='enter_detail',
            name='subject',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
